reporter: dot
timeout: 25000
exit: true
bail: true
spec:
# databasemock does not contain any tests, but is required for the test suite to run
# it contains before/after hooks so it can not be loaded with --require
# before any cjs tests the databasemock must be loaded here because it contains top level await
  - "test/mocks/databasemock.mjs"
  - "test/helpers/defer-logger.mjs"
  - "test/helpers/cleanup.mjs"

  - "test/databasemock.mjs"

  - "test/database.mjs"
  - "test/database/sorted.mjs"
  - "test/database/sets.mjs"
  - "test/database/list.mjs"
  - "test/database/keys.mjs"
  - "test/database/hash.mjs"

  - "test/password.mjs"
  - "test/emailer.mjs"
  - "test/categories.mjs"
  - "test/posts.mjs"
  - "test/posts/uploads.mjs"
  - "test/api.mjs"

  - "test/activitypub.mjs"
  - "test/activitypub/actors.mjs"
  - "test/activitypub/analytics.mjs"
  - "test/activitypub/feps.mjs"
  - "test/activitypub/notes.mjs"
  - "test/activitypub/signatures.mjs"
  - "test/activitypub/webfinger.mjs"

  - "test/authentication.mjs"
  - "test/batch.mjs"
  - "test/blacklist.mjs"
  - "test/build.mjs"
  - "test/controllers-admin.mjs"
  - "test/controllers.mjs"
  - "test/coverPhoto.mjs"
  - "test/feeds.mjs"
  - "test/file.mjs"
  - "test/flags.mjs"
  - "test/groups.mjs"
  - "test/i18n.mjs"
  - "test/image.mjs"
  - "test/locale-detect.mjs"
  - "test/messaging.mjs"
  - "test/meta.mjs"
  - "test/middleware.mjs"
  - "test/navigation.js"
  - "test/notifications.js"
  - "test/package-install.js"
  - "test/pagination.js"
  - "test/plugins-installed.js"
  - "test/plugins.js"
  - "test/pubsub.js"
  - "test/rewards.js"
  - "test/search-admin.js"
  - "test/search.js"
  - "test/settings.js"
  - "test/socket.io.js"
  - "test/template-helpers.js"
  - "test/tokens.js"
  - "test/topics.js"
  - "test/topics/events.js"
  - "test/topics/thumbs.js"
  - "test/translator.js"
  - "test/upgrade.js"
  - "test/uploads.js"
  - "test/user.js"
  - "test/user/custom-fields.js"
  - "test/user/emails.js"
  - "test/user/reset.js"
  - "test/user/uploads.js"
  - "test/utils.js"
ignore: "test/files/**"